=== oslokommune/composite-actions/build-gp-config/testdata-ci/dummy-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": ["type", "team", "dev"],
  "properties": {
    "type": { "type": "string" },
    "team": { "type": "string" },
    "monorepo": { "type": "boolean" },
    "infrastructureRepository": { "type": "string" },
    "dev": { "type": "object" },
    "prod": { "type": "object" }
  }
}

=== oslokommune/composite-actions/build-gp-config/testdata-python/only-dev.json
{
  "$schema": "schema.json",
  "type": "app",
  "team": "utviklerflyt",
  "monorepo": true,
  "infrastructureRepository": "pirates-iac",
  "dev": {
    "accountId": "123456789012",
    "name": "pirates-dev",
    "defaultRegion": "eu-west-1",
    "deploymentRoleArn": "arn:aws:iam::123456789012:role/pirates-dev-gha-app-deploy",
    "artifactRoleArn": "arn:aws:iam::123456789012:role/pirates-dev-gha-artifact-publish",
    "artifactBucketName": "pirates-dev-123456789012-artifact",
    "artifactEcrRepositoryName": "pirates-dev-artifact",
    "infrastructureRoot": "stacks/dev"
  }
}

=== oslokommune/composite-actions/build-gp-config/testdata-ci/dummy-config.json
{
  "$schema": "build-gp-config/testdata-ci/dummy-schema.json",
  "type": "app",
  "team": "test-team",
  "monorepo": true,
  "infrastructureRepository": "test-iac",
  "dev": {
    "accountId": "111111111111",
    "name": "test-dev",
    "defaultRegion": "eu-west-1",
    "deploymentRoleArn": "arn:aws:iam::111111111111:role/test-dev-deploy",
    "artifactRoleArn": "arn:aws:iam::111111111111:role/test-dev-artifact",
    "artifactBucketName": "test-dev-artifact",
    "artifactEcrRepositoryName": "test-dev-ecr",
    "infrastructureRoot": "stacks/dev"
  }
}

=== oslokommune/composite-actions/build-gp-config/testdata-python/full.json
{
  "$schema": "schema.json",
  "type": "app",
  "team": "utviklerflyt",
  "monorepo": true,
  "infrastructureRepository": "pirates-iac",
  "dev": {
    "accountId": "123456789012",
    "name": "pirates-dev",
    "defaultRegion": "eu-west-1",
    "deploymentRoleArn": "arn:aws:iam::123456789012:role/pirates-dev-gha-app-deploy",
    "artifactRoleArn": "arn:aws:iam::123456789012:role/pirates-dev-gha-artifact-publish",
    "artifactBucketName": "pirates-dev-123456789012-artifact",
    "artifactEcrRepositoryName": "pirates-dev-artifact",
    "infrastructureRoot": "stacks/dev"
  },
  "prod": {
    "accountId": "987654321012",
    "name": "pirates-prod",
    "defaultRegion": "eu-west-1",
    "deploymentRoleArn": "arn:aws:iam::987654321012:role/pirates-prod-gha-app-deploy",
    "artifactRoleArn": "arn:aws:iam::987654321012:role/pirates-prod-gha-artifact-publish",
    "artifactBucketName": "pirates-prod-987654321012-artifact",
    "artifactEcrRepositoryName": "pirates-prod-artifact",
    "infrastructureRoot": "stacks/prod"
  }
}
